language: java
jdk:
  - oraclejdk8
services:
  - docker
before_install:
  - docker network create dvs
  - docker run -d -p 8500:8500 --name=registry --network=dvs consul agent --dev -ui -client=0.0.0.0
  - docker exec -t registry curl -X PUT -d 'cache--6379----2--5--0' http://localhost:8500/v1/kv/ivan/RedisConnectionString
  - docker exec -t registry curl -X PUT -d 'neo4j://graph-db:7687' http://localhost:8500/v1/kv/ivan/DB_ConnectionString
  - docker exec -t registry curl -X PUT -d 'True' http://localhost:8500/v1/kv/ivan/StampTransactionId
  - docker exec -t registry curl -X PUT -d 'True' http://localhost:8500/v1/kv/ivan/AtomicTransactions
  - docker exec -t registry curl -X PUT -d 'Json' http://localhost:8500/v1/kv/ivan/Data_Format_Type
  - docker run -d --publish=7474:7474 --publish=7687:7687 --env=NEO4J_AUTH=none --volume=/home/abarry/neo4j/data:/data --network=dvs --name=graph-db neo4j
  - docker run --network=dvs --name=cache -d redis
  - docker run --name document-db -d --network=dvs mongo
  - sleep 3
  - docker run --name crazyivan --network=dvs -p 5555:5555 -d aostreetart/crazyivan:latest -consul-addr=registry:8500 -ip=localhost -port=5555 -log-conf=CrazyIvan/log4cpp.properties
  - sleep 3
  - docker logs --tail 50 registry
  - docker logs --tail 50 cache
  - docker logs --tail 50 document-db
  - docker logs --tail 50 graph-db
  - docker logs --tail 150 crazyivan
  - docker ps -a
install:
  - gradle assemble
script:
  - gradle check
notifications:
  slack:
    secure: "ircpf8VWCNE6NmnZR32X7hWmvcBmFaiS66dRPc4MJYEA1w+JnUGFrHa9tG4cRGFwcHxyXHW4Vv1zaoqkPM6tV33SmTRZf79YJdBC0GzboaUPfzxP5xYHQ3VofPp1s0utugM0KCq3yradLqSfmn5lTDLfpDBetMonhaLD5wgd3p0lKlNhg76M3MeTQVWrw66vMJKxX/7SOIPZYcPb7lwYEdT3/u9hWMWIrUJOxuYop8nucmUnROHKauHmSLyiSdK2uziUKiHN6FnVafuqst8rZcW0RWBGgms4e30K2FOA/dUjH8N2hXgrokQa13qZNIw/2q31sy3z4it1casYFtThQm6rEnXkdvPzSe4LCdKsSBFTfE2pKuK9ZWAXQtAb6H7h9Ce795emF2NlbvBixglAEpwyIo/jf+TbYSClcl1cv7yu2S26sfovGifgHAqLAiR3s5ExpQONhuj/AQXnWlDmP0GQWaQ2h44P7jb6+MPaiS6NF9g/43S0Kg3fxa6ccFB491ydo/t8TlRren0xcjl6BFB78sVc4Hy++AFYP3U0Umqhx+Yq+XJDnUnH4TFjg2N2xmdbzzqvM4WxqrD6e8gxJWCQ/4hqUlVfG/VEr9bwUBEcIJNhDcXDM31o95652//j9KPryHNIcWWBpWXMyzddwbdgJN80DSc7ycWG+iOLP0U="
