language: java
jdk:
  - oraclejdk8
before_install:
- wget https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_linux_amd64.zip
- unzip consul_0.6.4_linux_amd64.zip
- "./consul agent -dev -bind=127.0.0.1 &"
install:
- gradle assemble
script:
- gradle check
