version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.2
    container_name: logstash
    ports:
      - "12201:12201/udp"
    command: -e 'input { gelf {} } output { elasticsearch { hosts => [ "elasticsearch:9200" ] } }'
    depends_on:
      - "elasticsearch"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./kibana.yml:/usr/share/aesel/docker/elk/kibana/kibana.yml
    depends_on:
      - "elasticsearch"
  registry:
    image: consul
    container_name: registry
    ports:
      - "8500:8500"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    command: agent --dev -ui -client=0.0.0.0
    depends_on:
      - "logstash"
  config:
    image: aostreetart/populateaeselconfig:latest
    container_name: config
    command: ./populate_consul.sh registry
    depends_on:
      - "registry"
      - "logstash"
  cache:
    image: redis
    container_name: cache
  graphdb:
    image: neo4j
    container_name: graph-db
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ${HOME}/neo4j/data:/data
    environment:
      NEO4J_AUTH: none
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  documentdb:
    image: mongo
    container_name: document-db
    ports:
      - "27017:27017"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  queue:
    image: spotify/kafka
    container_name: queue
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      ADVERTISED_PORT: 9092
      ADVERTISED_HOST: "queue"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  crazyivan:
    image: aostreetart/crazyivan:latest
    container_name: crazyivan
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    ports:
      - "5555:5555"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    command: -consul-addr=registry:8500 -ip=localhost -advertised-host=crazyivan -port=5555 -log-conf=CrazyIvan/log4cpp.properties -wait=9
    depends_on:
      - "graphdb"
      - "cache"
      - "registry"
      - "config"
      - "queue"
  clyman:
    image: aostreetart/clyman:latest
    container_name: clyman
    ports:
      - "5556:5556"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    command: -consul-addr=registry:8500 -ip=localhost -advertised-host=clyman -port=5556 -log-conf=CLyman/log4cpp.properties -wait=9
    depends_on:
      - "documentdb"
      - "cache"
      - "registry"
      - "config"
      - "queue"
  adrestia:
    image: aostreetart/adrestia:latest
    container_name: adrestia
    ports:
      - "5885:5885"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    depends_on:
      - "registry"
    environment:
      SPRING_APPLICATION_JSON: '{"server":{"port":"5885","mongo":{"host":"document-db","port":"27017"},"zmq":{"redlist":{"duration":"10"},"greylist":{"duration":"10"},"blacklist":{"duration":"10"},"retries":"3","timeout":"10000"}},"management":{"port":"5885","address":"127.0.0.1"},"spring":{"application":{"name":"Adrestia"},"profiles":{"active":"dev"},"cloud":{"consul":{"host":"registry","discovery":{"preferIpAddress":false}}},"http":{"multipart":{"max-file-size":"128MB","max-request-size":"128MB"}}}}'
